mod compose;
mod docker;

#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run() {
    tauri::Builder::default()
        .plugin(tauri_plugin_opener::init())
        .manage(docker::LogHub::default())
        .manage(docker::TermHub::default())
        .manage(docker::LayerDiffCache::default())
        .invoke_handler(tauri::generate_handler![
            docker::engine_info,
            docker::list_containers,
            docker::container_start,
            docker::container_stop,
            docker::container_restart,
            docker::container_pause,
            docker::container_unpause,
            docker::container_rename,
            docker::container_open_terminal,
            docker::list_host_terminals,
            docker::container_term_start,
            docker::container_term_write,
            docker::container_term_resize,
            docker::container_term_stop,
            docker::container_remove,
            docker::container_inspect,
            docker::container_logs,
            docker::container_logs_stop,
            docker::list_images,
            docker::image_inspect,
            docker::image_history,
            docker::image_layer_diffs,
            docker::image_layer_file,
            docker::image_remove,
            docker::list_volumes,
            docker::volume_inspect,
            docker::volume_remove,
            docker::list_networks,
            docker::network_inspect,
            docker::network_remove,
            docker::image_pull,
            docker::image_search,
            docker::image_tag,
            docker::image_save,
            docker::image_load,
            docker::container_create,
            docker::container_stats,
            docker::containers_prune,
            docker::images_prune,
            docker::volumes_prune,
            docker::networks_prune,
            docker::system_df,
            docker::engine_events,
            docker::volume_create,
            docker::network_create,
            docker::network_connect,
            docker::network_disconnect,
            docker::container_fs_list,
            docker::container_fs_read,
            docker::container_fs_write,
            compose::compose_available,
            compose::stack_list,
            compose::stack_create,
            compose::stack_read,
            compose::stack_write,
            compose::stack_delete,
            compose::stack_up,
            compose::stack_down,
        ])
        .run(tauri::generate_context!())
        .expect("error while running tauri application");
}
